version: 2
jobs:
  linux_x64_win_x86:
    docker:
      - image: debian:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install -y g++ libsdl2-dev libsdl2-mixer-dev libsdl2-ttf-dev git rpm cmake libsodium-dev cmake gcc-mingw-w64-i686 g++-mingw-w64-i686 wget sudo
      - run: cmake -S. -Bbuild .. -DBINARY_RELEASE=ON -DCMAKE_BUILD_TYPE=MINSIZEREL
      - run: cmake --build build -j 2
      - run: cmake --build build -j 2 --target package
      - store_artifacts: {path: ./build/devilutionx, destination: devilutionx_linux_x86_64}
      - run: mkdir ./build/package && find build/_CPack_Packages/Linux/7Z/ -name 'devilutionx' -exec cp "{}" ./build/package/devilutionx \; && cp ./Packaging/resources/devilutionx.mpq ./build/package/devilutionx.mpq && mv ./build/devilutionx*.deb ./build/package/devilutionx.deb && mv ./build/devilutionx*.rpm ./build/package/devilutionx.rpm && mv ./build/CharisSILB.ttf ./build/package/CharisSILB.ttf && cp ./Packaging/nix/README.txt ./build/package/README.txt && cp ./Packaging/resources/LICENSE.CharisSILB.txt ./build/package/LICENSE.CharisSILB.txt
      - run: cd ./build/package/ && tar -cavf ../../devilutionx.tar.xz * && cd ../../
      - store_artifacts: {path: ./devilutionx.tar.xz, destination: devilutionx_linux_x86_64.tar.xz}
      - run: rm -rf build/*
      - run: Packaging/windows/mingw-prep.sh
      - run: cmake -S. -Bbuild -DBINARY_RELEASE=ON -DCMAKE_BUILD_TYPE=MINSIZEREL -DCMAKE_CXX_FLAGS="-static" -DCMAKE_C_FLAGS="-static" -DCMAKE_TOOLCHAIN_FILE=../CMake/mingwcc.cmake
      - run: cmake --build build -j 2
      - run: cmake --build build -j 2 --target package
      - store_artifacts: {path: ./build/devilutionx.exe, destination: devilutionx_x86.exe}
      - store_artifacts: {path: ./build/devilutionx.zip, destination: devilutionx_x86.zip}

workflows:
  version: 2
  testflow:
    jobs:
      - linux_x64_win_x86